project:
  type: website
  output-dir: _site
  preview:
    port: 8188

website:
  title: "Suryajith Chillara"
  site-url: https://suryajith.github.io
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: students/index.qmd
        text: Students
      - text: Teaching
        href: teaching/index.qmd
    right:
      - href: contact/index.qmd
        text: Contact
  open-graph: true
  
publish:
  - name: gh-pages
    url: https://suryajith.github.io
    branch: main
    render: true
  
format:
  html:
    theme: 
      - morph
    # js: scripts.js
    css: styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    include-after-body: _footer.qmd
    # page-layout: full
    # filters:
    #   - abstract-section




