---
title: "The Chasm at Depth Four, and Tensor Rank: Old results, new insights"
date: "2016-07-15"
year: "2016"
publisher: "Electron. Colloquium Comput. Complex. 23: 96 (2016)"
authors: "S. Chillara, M. Kumar, R. Saptharishi and V. Vinay"
---

[Link to the article](/storage/papers/d4tr.pdf)

### Authors
Suryajith Chillara, Mrinal Kumar, Ramprasad Saptharishi and V. Vinay

### Publisher Information
- Preprint: [Electron. Colloquium Comput. Complex. 23: 96 (2016)](https://eccc.weizmann.ac.il/report/2016/096/)

## Abstract
Agrawal and Vinay (2008) showed how any polynomial size arithmetic circuit can be thought of as a depth four arithmetic circuit of subexponential size. This unexpected depth reduction to constant depth is in contrast to circuits in the Boolean setting.
The resulting circuit size in this simulation was more carefully analyzed by Korian (2011) and subsequently by Tavenas (2013).
We provide a simple proof of this chain of results. We then abstract the main ingredient to apply it to formulas and constant depth circuits, and show more structured depth reductions for them.

In an apriori surprising result, Raz (2010) showed that for any $n$ and $d$, such that $ \omega(1) \leq d \leq  O\left(\frac{\log n}{\log\log n}\right)$, constructing explicit tensors $T:[n]^d \rightarrow \mathbb{F}$ of high enough rank would imply superpolynomial lower bounds for arithmetic formulas over the field $\mathbb{F}$. Using the additional structure we obtain from our proof of the depth reduction for arithmetic formulas, we give a new and arguably simpler proof of this connection. We also extend this result for homogeneous formulas to show that, in fact, the connection holds for any $d$ such that $\omega(1) \leq d \leq n^{o(1)}$.
